### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by deepakprabhakara** [boxyhq/phoenix#8]
- [ ] Blog
- [x] Success Stories
- [ ] Pricing section
- [x] Company pages
- [x] Announcement bar
- [ ] Open external links in a new tab
- [ ] Can we keep the top navbar on all pages including docs, guides, etc.
- [ ] Order of the sidebar needs to match the current website
- [ ] Title of the md files not being picked up correctly
- [ ] We are missing breadcrumbs in the docs, guides, etc. sections
- [ ] Turn off dark mode selection for now
- [ ] Can we have the search bar everywhere that searches across entire website content
